### PR TITLE
Add dhall-containerfile

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by kukimik** [comment]
I think this should get merged. The package is listed on https://dhall-lang.org (Packages/Docker), so it probably also deserves a place here.

**Review by Gabriella439 — APPROVED** [review]

**Comment by kukimik** [comment]
@TristanCacqueray Could you find a moment to handle the conflict? I would do it myself, but the source branch of the PR is the `master` branch of your fork and I didn't want to mess with it.

**Comment by TristanCacqueray** [comment]
@kukimik sure, it should be good now.

**Comment by kukimik** [comment]
Thanks!

**Pull request merged**
